# Generated by Django 6.1.2 on 2026-10-07 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asistencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_documento', models.CharField(max_length=2)),
                ('documento', models.CharField(max_length=11)),
                ('nombres', models.CharField(max_length=30)),
                ('apellidos', models.CharField(max_length=30)),
                ('whatsapp', models.CharField(max_length=10)),
                ('fecha', models.DateField()),
                ('asistio', models.BooleanField(default=True)),
            ],
        ),
    ]
